### ISSUE TITLE
Issues with local polyglot-v2 and current 2.0 version

### ISSUE THREAD

**Issue by psmith3** [UniversalDevicesInc/tesla-nodeserver#9]
Hi, I have not yet been able to get this nodeserver to work on my local polyglot-v2 server. The cloud server works fine. I have tried creating a custom configuration key of 'Tesla account email' and 'Tesla account password' for my respective Tesla username and password. Are those the right key names for these fields?

Regardless, the nodeserver errors out if I try to install from the node store in the GUI. I have since used git to clone the repository into my nodeserver directory and installed in a slot on my ISY. I cannot get the nodeserver to start and see this error in my log.
`12/14/2019, 6:18:04 PM - info: NS: Starting Local NodeServer Tesla profile number 7 :: Version 2.0.0
12/14/2019, 6:18:04 PM - error: NSChild STDERR: Tesla: /usr/bin/env: 'node': No such file or directory

12/14/2019, 6:18:04 PM - debug: NSChild Exit: Tesla exited with cause code: 127 and signal: null
12/14/2019, 6:18:04 PM - info: Tesla(7): NodeServer Disconnected.`

Does anyone else see this? Where exactly is this /usr/bin/env: 'node' supposed to be?

**Comment by blakevh** [comment]
I am running on-premise using an Raspberry Pi.  Do you get the first node (controller) when you add the Tesla nodeserver?  The first screenshot below is from the configuration page
![image](https://user-images.githubusercontent.com/6832052/70855347-fb634e00-1e8e-11ea-8b97-4f2cf4a7e8b8.png)
and the second screenshot is of the controller node
![image](https://user-images.githubusercontent.com/6832052/70855369-4b421500-1e8f-11ea-9c56-18a6d0f80804.png)

Did the controller node get created?

**Comment by psmith3** [comment]
It was a missing nodejs and up to date npm on the Debian:stretch image I was using. Got it working now. Thank you
